### ISSUE TITLE
modleing中的nlp报错

### ISSUE THREAD

**Issue by lympassion** [Zachary-Su/2020MCM#1]
你好，我美赛现在在练题，对于C题参考你们的代码，但是modelling.py中有两个地方报错，
1. `doc = nlp(" ".join(sent))`
     提示nlp未定义，我看了代码中的确只有一个nlp，请问你们但是是在那里定义的呢
2. `stats.kendalltau(data1.values, data2.values)`
     同样也是`data1`和`data2`未定义，这个应该怎么弄呢

**Comment by lukan217** [comment]
首先非常感谢你们能阅读我们的代码（没想到居然还有人看），这个代码是我一年前写的了，那时候代码水平不高，而且只是为了应付比赛，所以写出来可读性非常差，那几个.py文件都是从work.ipynb里面导出来的，所以copy的时候可能出错了，你可以只看work.ipynb，但是限于个人水平，里面代码质量也很差，你们参考一下就好了。
针对你的第一个问题，nlp = spacy.load('en', disable=['parser', 'ner'])，在work.ipynb里面有
针对你的第二个问题，那个应该是我自己测试用的，可直接删去。
最后祝取得好成绩！

**Comment by lympassion** [comment]
感谢回复，知道了
